import "./globals.css";

import { ReactNode } from "react";
import type { Metadata } from "next";
import { GeistMono } from "geist/font/mono";

import { Toaster } from "@/components/ui/toaster";
import DesignerContextProvider from "@/components/form-builder/context/designer";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { FormThemeProvider } from "@/components/providers/form-theme-provider";

const geistMono = GeistMono;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={geistMono.className}>
        <DesignerContextProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <FormThemeProvider>
              {children}
              <Toaster />
            </FormThemeProvider>
          </ThemeProvider>
        </DesignerContextProvider>
      </body>
    </html>
  );
}
